version: "3.9"
services:
  postgres:
    image: postgres:14.8-alpine3.18
    container_name: pgdb-test
    command:
      - "postgres"
      - "-c"
      - "max_connections=50"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=4GB"
      - "-c"
      - "work_mem=16MB"
      - "-c"
      - "maintenance_work_mem=512MB"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "temp_file_limit=10GB"
      - "-c"
      - "log_min_duration_statement=200ms"
      - "-c"
      - "idle_in_transaction_session_timeout=10s"
      - "-c"
      - "lock_timeout=1s"
      - "-c"
      - "statement_timeout=60s"
      - "-c"
      - "shared_preload_libraries=pg_stat_statements"
      - "-c"
      - "pg_stat_statements.max=10000"
      - "-c"
      - "pg_stat_statements.track=all"
      # -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    environment:
      POSTGRES_DB: "car_service"
      POSTGRES_USER: "tampio"
      POSTGRES_PASSWORD: "5130904/10002"
    volumes:
      - .:/docker-entrypoint-initdb.d
      - car_service-data:/var/lib/postgresql/data
        # ./postgresql.conf:/var/lib/postgresql/data/postgresql.conf
        # - ./logs:/logs
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tampio -d car_service"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
          limits:
            cpus: '1'
            memory: 4G
    networks:
      - postgres

  pgadmin:
    container_name: pgdb-test-pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      PGADMIN_DEFAULT_EMAIL: "tampio@nico.ni"
      PGADMIN_DEFAULT_PASSWORD: "5130904/10002"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

#  postgres_exporter:
#    container_name: pgdb-test-metrics_exporter
#    image: prometheuscommunity/postgres-exporter:v0.10.1
#    environment:
#      DATA_SOURCE_URI: "postgres:5432/testdb?sslmode=disable"
#      DATA_SOURCE_USER: "nico"
#      DATA_SOURCE_PASS: "yazawa"
#      PG_EXPORTER_EXTEND_QUERY_PATH: "/etc/postgres_exporter/queries.yaml"
#    volumes:
#      - ./queries.yaml:/etc/postgres_exporter/queries.yaml:ro
#    ports:
#      - "9187:9187"
#    restart: unless-stopped
#   deploy:
#      resources:
#        limits:
#          cpus: '0.2'
#          memory: 500M
#    networks:
#      - postgres

volumes:
  car_service-data:
  pgadmin-data:

networks:
  postgres:
    driver: bridge
